complaint/urls.py
from django.urls import path
from .models import Complaint
from . import views

app_name = 'complaint'

urlpatterns = [
    # complaint views

    path('', views.home, name='home'),
    
    # Complaint form
    path('complaint/', views.complaint, name='complaint'),

    # For about
    path('about/', views.about, name='about'),

    # For complaint status
    path('status/', views.status, name='status'),

    # for admin to see and edit the status of complaints
    path('complaint_list/', views.complaint_list, name='complaint_list'),

    # Edit option for admin to edit the status
    path('edit/<int:complaint_id>/', views.edit, name='edit'),
]

fir/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('complaint.urls', namespace='complaint')),
    path('users/', include('users.urls')),
]

users/urls.py
from django.urls import path, include


app_name = 'users'
urlpatterns = [
    # Default auth urls for login and logout
    path('', include('django.contrib.auth.urls')),
    
]

complaint/models.py
from django.db import models
from django.utils import timezone

# Create your models here.


class Complaint(models.Model):
    STATUS_CHOICES = (
        ('pending', 'Pending'),
        ('entertained', 'Entertained'),
    )
    GENDER_CHOICES = (
        ('male', 'Male'),
        ('female', 'Female'),
        ('trans', 'Trans'),
    )
    COMPLAINT_CHOICES = (
        ('misbehave', 'Misbehave'),
        ('illegal gratification', 'Illegal Gratification'),
        ('faulty investigation', 'Faulty Investigation'),
        ('manhandling', 'Manhandling'),
        ('non registration of cases', 'Non registration of cases'),
        ('traffic', 'Traffic'),
        ('other', 'Other')
    )
    AGAINST_CHOICES = (
        ('public', 'Public'),
        ('police', 'Police'),
    )
    ADRESSED_TO_CHOICES = (
        ('IGP', 'IGP'),
        ('DIG OPS', 'DIG OPS'),
        ('other', 'OTHER'),
    )
    CITY_CHOICES = (
        ('islamabad', 'Islamabad'),
        ('lahore', 'Lahore'),
        ('peshawar', 'Peshawar'),
        ('karachi', 'Karachi'),
        ('other', 'Other'),
    )
    complaint_for = models.CharField(max_length=25, choices=COMPLAINT_CHOICES, default='Misbehave')
    name = models.CharField(max_length=50)
    cnic = models.CharField(verbose_name='CNIC', max_length=13, unique=True)
    gender = models.CharField(max_length=6, choices=GENDER_CHOICES, default='Trans')
    address = models.CharField(max_length=250)
    city = models.CharField(max_length=20, choices=CITY_CHOICES , default='Islamabad')
    phone = models.CharField(max_length=11)
    email = models.EmailField()
    against = models.CharField(max_length=10, choices=AGAINST_CHOICES, default='Public')
    complaint_details = models.TextField(max_length=1800)
    adressed_to = models.CharField(max_length=15, choices=ADRESSED_TO_CHOICES, default='IGP')
    
    created = models.DateTimeField(auto_now_add=True)

    status = models.CharField(max_length=11, choices=STATUS_CHOICES, default='pending')



    class Meta:
        ordering = ('-status',)

    def __str__(self):
        return self.complaint_for.title()

users/models.py
from django.db import models

# Create your models here.

complaint/forms.py
from .models import Complaint
from django import forms

class ComplaintForm(forms.ModelForm):
    class Meta:
        model = Complaint
        fields = ['complaint_for', 'name', 'cnic', 'gender', 'address', 'city', 'phone', 'email', 'against', 'complaint_details', 'adressed_to']
        widgets = {
            'name': forms.TextInput(attrs={'placeholder': 'Full name'}),
            'cnic': forms.TextInput(attrs={'placeholder': 'without dashes'}),
            'phone': forms.TextInput(attrs={'placeholder': 'without dash'}),
            'email': forms.TextInput(attrs={'placeholder': 'someone@example.com'}),
            'complaint_details': forms.Textarea(attrs={'placeholder': 'Please limit your text to 1800 characters only'}),
        }

class StatusForm(forms.Form):
    nic = forms.CharField(max_length=13)


class EditComplaintForm(forms.ModelForm):
    class Meta:
        model = Complaint
        fields = ['status']

complaint/views.py
from django.shortcuts import render, redirect
from .models import Complaint
from .forms import ComplaintForm, StatusForm, EditComplaintForm
from django.contrib.auth.decorators import login_required
# for twilio sms service
from twilio.rest import Client



# for email
from django.core.mail import send_mail
from django.conf import settings

from django.shortcuts import get_object_or_404

# Create your views here.


def home(request):
    return render(request, 'complaint/home.html')

def complaint(request):
    if request.method != 'POST':
        form = ComplaintForm()

    else:
        form = ComplaintForm(data=request.POST)
        if form.is_valid():
            form.save()
            # Send email functionlity
            subject = 'Online Complaint System'
            message = 'Your complaint has been filed succesfully at online complaint portal.'
            email_from = settings.EMAIL_HOST_USER
            send_to = form.cleaned_data['email']
            recipient_list = [send_to]

            send_mail(subject, message, email_from, recipient_list)


            # # sms functionality
            # # Your Account SID from twilio.com/console
            # account_sid = "ACa5f76db99b4487f41591f766088ac12c"
            # # Your Auth Token from twilio.com/console
            # auth_token = "b7b094b45326bad5bbf08856ba82e189"

            # client = Client(account_sid, auth_token)

            # con = form.cleaned_data['phone']
            # contact = '+92'+ con[1:]
            # message = client.messages.create(
            # to=contact,
            # from_="+18603984426",
            # body="Your complaint has been successfully filed. It will take a week or two to entertain your case.")
            # print(message.sid)

            return redirect('complaint:home')

    context = {'form': form}
    return render(request, 'complaint/complaint_form.html', context)


def status(request):
    if request.method != 'POST':
        result = 'None'
        form = StatusForm()

    else:
        form = StatusForm(data=request.POST)
        if form.is_valid():
            nic = form.cleaned_data['nic']
            complaint = get_object_or_404(Complaint, cnic=nic)
            result = complaint

    return render(request, 'complaint/status.html', {'form': form, 'result': result})

# This will need login_required decorators cause only admin can see this
@login_required
def complaint_list(request):
    pen_complaints = Complaint.objects.filter(status='pending')
    ent_complaints = Complaint.objects.filter(status='entertained')

    
    return render(request, 'complaint/complaint_list.html', {'pen_complaints': pen_complaints, 'ent_complaints': ent_complaints})


@login_required
def edit(request, complaint_id):
    complaint = Complaint.objects.get(id=complaint_id)
    email = complaint.email

    if request.method != 'POST':
        form = EditComplaintForm(instance=complaint)

    else:
        form = EditComplaintForm(instance=complaint, data=request.POST)
        if form.is_valid():
            
            # SEND EMAIL FUNCTIONALITY
            if form.cleaned_data['status'] != 'pending':
                subject = 'Online Complaint System'
                message = 'Your complaint has been successfully updated. You can check your complaint status on the portal.'
                email_from = settings.EMAIL_HOST_USER
                recipient_list = [email]

                send_mail(subject, message, email_from, recipient_list)

            form.save()
            return redirect('complaint:complaint_list')

    context = {'complaint': complaint, 'form': form}
    return render(request, 'complaint/edit.html', context)


def about(request):
    return render(request, 'complaint/about.html')

users/views.py
from django.shortcuts import render

# Create your views here.

complaint/templates/complaint/about.html
{% extends 'complaint/base.html' %}
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">

<head>
    <title>About</title>
</head>

<body>
    {% block header %}
    <div style="height: 100px; background: lightgrey; padding: 35px; color: black; text-align: right;">
        Home/About
    </div>
    <div style="text-align: center;">
        <p>
            <img src="{% static 'complaint/about1.jpg' %}" alt="about1">
            <img src="{% static 'complaint/about2.jpg' %}" alt="about2">
            <img src="{% static 'complaint/about3.jpg' %}" alt="about3">
            <img src="{% static 'complaint/about4.jpg' %}" alt="about4">
            <img src="{% static 'complaint/about5.jpg' %}" alt="about5">

        </p>
    </div>
    {% endblock header %}

    {% block content %}

    <div>
        <p>Islamabad Capital Police came into existence w.e.f 1st Jan 1981 by virtue of presidential order no. 17 & 18 of 1980 to fulfill the need for separate Police organization for the federal capital, Islamabad, to enforce the law, protect property, and limit civil disorder. To ensure preservation of peace and public safety through the enforcement of local, state, and Federal laws, and by providing support and assistance during emergency or crisis situations
        </p>
        <hr>
        <h4 class="heading">Establishment</h4>
        <p>Islamabad Police is regulated by Central Police Office, which involves three Divisions, Islamabad Model
            Traffic
            Police, Islamabad Police Information Technology Branch and centralized command & control center. Total
            sanctioned strength of ICT Police is 12004. Commander of the ICT Police is termed as Inspector General of
            Police, who is senior bureaucrat of Police Service of Pakistan. Current Commander of the ICT Police is
            Muhammad
            Aamir Zulfiqar Khan. Mr. Aamir Zulfiqar Khan is a seasoned police officer with rich experience of not only
            field
            service but as well as staff assignment including human resources, development and financial management, He
            has
            vast international exposure on various assignments. Muhammad Aamir Zulfiqar Khan is playing vital role in
            Police
            reforms by taking revolutionary steps in changing traditional Police Stations into e-powered Model Police
            Stations. Divisions of the ICT Police are headed by their respective Deputy Inspectors General of Police,
            whereas Islamabad Model Traffic Police is headed by the Senior Superintendent of Police, and the Information
            Technology Branch by Director-Information Technology. Special Branch is another specialized entity, headed
            by
            the Assistant Inspector General of Police. Territory of Islamabad is covered by 22 Police Stations.
        </p>
        <hr>
        <h4 class="heading">Objectives</h4>
        <p>• Provide safe, secure and public friendly ecology to the citizens of Islamabad.
            • Effective maintenance of law and order.
            • Prevention and detection of crime.
            • Efficient and smooth flow of traffic on the pattern of advanced traffic systems of the world.
            • Protection of President and Prime Minister of Pakistan, Heads of the states and foreign dignitries
            visiting
            Islamabad, Foreign Diplomats residing in Islamabad and vital installations.
            • Intelligence gathering to fulfill the objectives of police, traffic and security.
            • Encourage public participation in the fight against crime – CPLC, public conciliatory committees, and
            human
            rights watch group.
            • Help the citizens in times of distress – rescue-15.
        </p>
        <hr>
        <h4 class="heading">Islamabad at Glance</h4>
        <p>With a population of two million, it is the 10th largest city of Pakistan, while the larger
            Islamabad-Rawalpindi
            metropolitan area is the third largest in Pakistan with population exceeding five million.
        </p>
    </div>
    {% endblock content %}
</html>

complaint/templates/complaint/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <title>Online Complaint Cell</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
        integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

</head>
<style>
    .link {
        font-size: large;
    }

    .container {
        font-family: Arial, Helvetica, sans-serif;
        font-size: large;
        width: 80%;
        margin: auto;
        margin-top: 5px;
    }

    #footer {
        height: 60px;
        text-align: center;
        padding: 20px;
        background: #444444;
        color: white;
        width: 100%;
        position: absolute;
        left: 0;
        bottom: 0;
        width: 100%;
    }

    html {
        position: relative;
        min-height: 100%;
    }

    body {
        margin: 0 0 100px;
    }
</style>

<body>
    <!--navbar start -->

    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a style="font-size: xx-large;" class="navbar-brand" href="{% url 'complaint:home' %}">Home</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">

                {% if user.is_authenticated %}
                <li class="nav-item active">
                    <a class="nav-link link" href="{% url 'complaint:complaint_list' %}">Complaints<span
                            class="sr-only">(current)</span></a>
                </li>
                {% else %}
                <li class="nav-item active">
                    <a class="nav-link link" href="{% url 'complaint:complaint' %}">Complaint<span
                            class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link link" href="{% url 'complaint:status' %}">Check Complaint Status<span
                            class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link link" href="{% url 'complaint:about' %}">About<span
                            class="sr-only">(current)</span></a>
                </li>
                {% endif %}
                
            </ul>

            {% if user.is_authenticated %}
            Hello, {{ user.username.capitalize }} |
            <a class="nav-link logout" href="{% url 'users:logout' %}">Logout</a>
            {% else %}
            <a class="link" href="{% url 'users:login' %}">Admin Login</a>
            {% endif %}


        </div>
    </nav>

    <!--navbar finish -->

    {% block header %}
    {% endblock header %}

    <div class="container">
        <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
        <script>
            $(document).ready(function () {
                $('.logout').click(function () {
                    if (confirm('Are you sure to logout')) {
                        return true;
                    }
                    return false;
                });

            });
        </script>
        <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"
            integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n"
            crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
            integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
            crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
            integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6"
            crossorigin="anonymous"></script>


            
        {% block content %}{% endblock %}

    </div>
    <div id="footer">
        <p>COPYRIGHT Ⓒ LADDAN JAFRI. ALL RIGHTS RESERVED</p>
    </div>
</body>
</html>

complaint/templates/complaint/complaint_form.html
{% extends 'complaint/base.html' %}
{% load bootstrap4 %}
<!DOCTYPE html>
<html lang="en">

<head>
    <title>Complaint</title>
</head>

<body>

    {% block content %}
    <div style="width: 50%;">
        <h3 style="text-align: center; padding-top: 10px;">File a new Complaint</h3>
        <hr>
        <form class="form-group" action="{% url 'complaint:complaint' %}" method="POST">
            {% csrf_token %}
            {% bootstrap_form form %}
            <button class="btn btn-primary" name="submit">Save</button>

            <!-- This is an input field to redirect when user login -->
            <input type="hidden" name="next" value="{% url 'complaint:home' %}" />
        </form>
    </div>
    {% endblock content %}
</body>

</html>

complaint/templates/complaint/complaint_list.html
{% extends 'complaint/base.html' %}
<!DOCTYPE html>
<html lang="en">

<head>
    <title>Document</title>
</head>

<body>

    {% block content %}

    <!-- start  -->

    <div class="card text-center">
        <div class="card-header">
            <ul class="nav nav-tabs card-header-tabs myclass">
                <li class="nav-item">
                    <a class="nav-link first" href="#">Pending</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link second" href="#">Entertained</a>
                </li>
            </ul>
        </div>
        <div class="card-body">
            <div class="pending">
                {% for complaint in pen_complaints %}
                <ul style="text-align: left;">
                    <h3>
                        <li>Complaint: {{complaint}}</li>
                    </h3> Filed by {{ complaint.name}} at <i><small>{{ complaint.created }}</small></i>
                    <p>
                        <a href="{% url 'complaint:edit' complaint.id %}">Update status</a>
                    </p>
                    <hr>
                </ul>
                {% endfor %}
            </div>
            <div class="entertained">
                {% for complaint in ent_complaints %}
                <ul style="text-align: left;">
                    <h3>
                        <li>Complaint: {{complaint}}</li>
                    </h3> Filed by {{ complaint.name}} at <i><small>{{ complaint.created }}</small></i>
                    <hr>
                    <!-- <p>
                        <a href="{% url 'complaint:edit' complaint.id %}">Update status</a>
                    </p> -->
                </ul>
                {% endfor %}
            </div>

        </div>
    </div>

    <!-- finish -->

    <script>
        $(document).ready(function () {
            $('.first').addClass('active')
            $('.entertained').hide()

            $('.first').click(function () {
                $('.first').addClass('active')
                $('.second').removeClass('active')
                $('.pending').show()
                $('.entertained').hide()
            })
            $('.second').click(function () {
                $('.second').addClass('active')
                $('.first').removeClass('active')
                $('.pending').hide()
                $('.entertained').show()
            });

        });

    </script>
    {% endblock content %}
</body>

</html>

complaint/templates/complaint/edit.html
{% extends 'complaint/base.html' %}


{% block content %}


<div class="card" style="width: 60%; margin: auto;">
    <div class="card-header">
        <h4 style="text-align: center; padding-top: 10px">Update status for <small><b>{{complaint}}</b></small> filed by
            <small><b>{{ complaint.name.capitalize }}</b></small> having Nic: <small><b>{{complaint.cnic}}</b></small>
        </h4>
    </div>
    <div class="card-body">
        <h5 class="card-title">Complaint time: <small>{{ complaint.created}}</small</h5> <br><br>
                <form action="{% url 'complaint:edit' complaint.id %}" method="POST">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button class="btn btn-primary" name="submit">Update</button>
                </form>
    </div>
</div>

{% endblock content %}

complaint/templates/complaint/home.html
{% extends 'complaint/base.html' %}
{% load staticfiles %}


{% block header %}

<div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
    <ol class="carousel-indicators">
        <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
        <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
        <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
        <li data-target="#carouselExampleIndicators" data-slide-to="3"></li>
        <li data-target="#carouselExampleIndicators" data-slide-to="4"></li>

    </ol>
    <div class="carousel-inner">
        <div class="carousel-item active">
            <img src="{% static 'complaint/slide1.png' %}" class="d-block w-100" alt="slider image 1">
        </div>
        <div class="carousel-item">
            <img src="{% static 'complaint/slide2.png' %}" class="d-block w-100" alt="slider image 2">
        </div>
        <div class="carousel-item">
            <img src="{% static 'complaint/slide3.png' %}" class="d-block w-100" alt="slider image 3">
        </div>
        <div class="carousel-item">
            <img src="{% static 'complaint/slide4.png' %}" class="d-block w-100" alt="slider image 4">
        </div>
        <div class="carousel-item">
            <img src="{% static 'complaint/slide5.png' %}" class="d-block w-100" alt="slider image 5">
        </div>
    </div>
    <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
    </a>
    <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
    </a>
</div>
{% endblock header %}

{% block content %}

<br>

<div>
    <h1 style="text-align: center;" class="display-4">Complaint Portal</h1>
    <p>NOTE: FALSE COMPLAINT REPORTING, MEANT TO INJURE OR ANNOY ANY PERSON, IS A CRIME UNDER PAKISTAN PENAL CODE
        SECTION 182 AND PUNISHABLE BY LAW FOR UP TO 6 MONTHS OR FINE OR WITH BOTH. THE IP ADDRESS WILL BE RECORDED ALONG
        WITH OTHER INFORMATION WHICH CAN BE USED TO IDENTIFY AND TRACK A FALSE COMPLAINER. </p>
    <p>You can check the status of your previously filed complaint (if any) here or file a new complaint below</p>
    {% if not user.is_authenticated %}
        <a class="btn btn-primary" href="{% url 'complaint:complaint' %}" role="button">Submit a Complaint</a>
    {% endif %}
</div>
<ul>
    <h2 style="color: blue;">Functionalities to be added</h2>
    <li>
        <h4>SMS functionality</h4>
    </li>
    <li>
        <h4>Heroku deployment</h4>
    </li>
</ul>
{% endblock %}

complaint/templates/complaint/status.html
{% extends 'complaint/base.html' %}
{% load bootstrap4 %}
<head>

</head>

<!-- form and result are coming in this template -->


{% block content %}

<div class="card" style="width: 60%; margin: auto;">

    {% if result == 'None' %}

    <div class="card-header">
        <h3 style="text-align: center; padding-top: 10px;">Enter Nic to check the complaint status.
        </h3>
    </div>
    <div class="card-body">
        <form action="{% url 'complaint:status' %}" method="POST">
            {% csrf_token %}
            <div style="width: 40%;">
                {% bootstrap_form form %}
            </div>
            <button class="btn btn-primary" name="submit">Search</button>
        </form>
    </div>

    {% else %}
    <div class="card-header">
        <h2>Status</h2>
    </div>
    <div class="card-body">

        <h4>Complaint: {{ result }}</h4>
        <h4>Filed by: {{ result.name }}</h4>
        <h4>Date: {{ result.created }}</h4>
        <h4>Status: {{ result.status.capitalize }}</h4>
    </div>

    {% endif %}

</div>

{% endblock content %}